import { socialLinks } from '@/lib/content/portfolio';

export type PhotoSpan = 'tall' | 'wide' | 'square';

export type CreativePhoto = {
  id: string;
  /** Grid thumbnail (640px, lazy-loaded). */
  src: string;
  /** Full-resolution image shown in the lightbox (2048px). */
  full: string;
  /** Intrinsic dimensions — used to reserve space and avoid layout shift. */
  w: number;
  h: number;
  span: PhotoSpan;
  alt: string;
};

/** Full photography portfolio — opened from the gallery CTA. */
export const lightroomAlbumUrl =
  socialLinks.lightroom ||
  'https://lightroom.adobe.com/shares/45147027c45043718f1a32ba10bdef66';

/**
 * Imported from the Lightroom album. Grid images live in
 * `public/gallery/grid` (640px) and full-size in `public/gallery/full` (2048px).
 * To refresh: re-export from Lightroom and replace the files, keeping names.
 */
export const creativePhotos: CreativePhoto[] = [
  {
    id: 'p01',
    src: '/gallery/grid/01.jpg',
    full: '/gallery/full/01.jpg',
    w: 2000,
    h: 3000,
    span: 'tall',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p02',
    src: '/gallery/grid/02.jpg',
    full: '/gallery/full/02.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p03',
    src: '/gallery/grid/03.jpg',
    full: '/gallery/full/03.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p04',
    src: '/gallery/grid/04.jpg',
    full: '/gallery/full/04.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p05',
    src: '/gallery/grid/05.jpg',
    full: '/gallery/full/05.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p06',
    src: '/gallery/grid/06.jpg',
    full: '/gallery/full/06.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p07',
    src: '/gallery/grid/07.jpg',
    full: '/gallery/full/07.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p08',
    src: '/gallery/grid/08.jpg',
    full: '/gallery/full/08.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p09',
    src: '/gallery/grid/09.jpg',
    full: '/gallery/full/09.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p10',
    src: '/gallery/grid/10.jpg',
    full: '/gallery/full/10.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p11',
    src: '/gallery/grid/11.jpg',
    full: '/gallery/full/11.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p12',
    src: '/gallery/grid/12.jpg',
    full: '/gallery/full/12.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p13',
    src: '/gallery/grid/13.jpg',
    full: '/gallery/full/13.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p14',
    src: '/gallery/grid/14.jpg',
    full: '/gallery/full/14.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p15',
    src: '/gallery/grid/15.jpg',
    full: '/gallery/full/15.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p16',
    src: '/gallery/grid/16.jpg',
    full: '/gallery/full/16.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p17',
    src: '/gallery/grid/17.jpg',
    full: '/gallery/full/17.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p18',
    src: '/gallery/grid/18.jpg',
    full: '/gallery/full/18.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p19',
    src: '/gallery/grid/19.jpg',
    full: '/gallery/full/19.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p20',
    src: '/gallery/grid/20.jpg',
    full: '/gallery/full/20.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p21',
    src: '/gallery/grid/21.jpg',
    full: '/gallery/full/21.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p22',
    src: '/gallery/grid/22.jpg',
    full: '/gallery/full/22.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p23',
    src: '/gallery/grid/23.jpg',
    full: '/gallery/full/23.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p24',
    src: '/gallery/grid/24.jpg',
    full: '/gallery/full/24.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p25',
    src: '/gallery/grid/25.jpg',
    full: '/gallery/full/25.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p26',
    src: '/gallery/grid/26.jpg',
    full: '/gallery/full/26.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p27',
    src: '/gallery/grid/27.jpg',
    full: '/gallery/full/27.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p28',
    src: '/gallery/grid/28.jpg',
    full: '/gallery/full/28.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p29',
    src: '/gallery/grid/29.jpg',
    full: '/gallery/full/29.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p30',
    src: '/gallery/grid/30.jpg',
    full: '/gallery/full/30.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p31',
    src: '/gallery/grid/31.jpg',
    full: '/gallery/full/31.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p32',
    src: '/gallery/grid/32.jpg',
    full: '/gallery/full/32.jpg',
    w: 3024,
    h: 4032,
    span: 'tall',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p33',
    src: '/gallery/grid/33.jpg',
    full: '/gallery/full/33.jpg',
    w: 3024,
    h: 4032,
    span: 'tall',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p34',
    src: '/gallery/grid/34.jpg',
    full: '/gallery/full/34.jpg',
    w: 3024,
    h: 4032,
    span: 'tall',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p35',
    src: '/gallery/grid/35.jpg',
    full: '/gallery/full/35.jpg',
    w: 3024,
    h: 4032,
    span: 'tall',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p36',
    src: '/gallery/grid/36.jpg',
    full: '/gallery/full/36.jpg',
    w: 3024,
    h: 4032,
    span: 'tall',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p37',
    src: '/gallery/grid/37.jpg',
    full: '/gallery/full/37.jpg',
    w: 3024,
    h: 4032,
    span: 'tall',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p38',
    src: '/gallery/grid/38.jpg',
    full: '/gallery/full/38.jpg',
    w: 3024,
    h: 4032,
    span: 'tall',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p39',
    src: '/gallery/grid/39.jpg',
    full: '/gallery/full/39.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p40',
    src: '/gallery/grid/40.jpg',
    full: '/gallery/full/40.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p41',
    src: '/gallery/grid/41.jpg',
    full: '/gallery/full/41.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p42',
    src: '/gallery/grid/42.jpg',
    full: '/gallery/full/42.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p43',
    src: '/gallery/grid/43.jpg',
    full: '/gallery/full/43.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p44',
    src: '/gallery/grid/44.jpg',
    full: '/gallery/full/44.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p45',
    src: '/gallery/grid/45.jpg',
    full: '/gallery/full/45.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p46',
    src: '/gallery/grid/46.jpg',
    full: '/gallery/full/46.jpg',
    w: 4016,
    h: 6016,
    span: 'tall',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p47',
    src: '/gallery/grid/47.jpg',
    full: '/gallery/full/47.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p48',
    src: '/gallery/grid/48.jpg',
    full: '/gallery/full/48.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p49',
    src: '/gallery/grid/49.jpg',
    full: '/gallery/full/49.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p50',
    src: '/gallery/grid/50.jpg',
    full: '/gallery/full/50.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p51',
    src: '/gallery/grid/51.jpg',
    full: '/gallery/full/51.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p52',
    src: '/gallery/grid/52.jpg',
    full: '/gallery/full/52.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p53',
    src: '/gallery/grid/53.jpg',
    full: '/gallery/full/53.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p54',
    src: '/gallery/grid/54.jpg',
    full: '/gallery/full/54.jpg',
    w: 4016,
    h: 6016,
    span: 'tall',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p55',
    src: '/gallery/grid/55.jpg',
    full: '/gallery/full/55.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p56',
    src: '/gallery/grid/56.jpg',
    full: '/gallery/full/56.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p57',
    src: '/gallery/grid/57.jpg',
    full: '/gallery/full/57.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p58',
    src: '/gallery/grid/58.jpg',
    full: '/gallery/full/58.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p59',
    src: '/gallery/grid/59.jpg',
    full: '/gallery/full/59.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p60',
    src: '/gallery/grid/60.jpg',
    full: '/gallery/full/60.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p61',
    src: '/gallery/grid/61.jpg',
    full: '/gallery/full/61.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p62',
    src: '/gallery/grid/62.jpg',
    full: '/gallery/full/62.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p63',
    src: '/gallery/grid/63.jpg',
    full: '/gallery/full/63.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p64',
    src: '/gallery/grid/64.jpg',
    full: '/gallery/full/64.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p65',
    src: '/gallery/grid/65.jpg',
    full: '/gallery/full/65.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p66',
    src: '/gallery/grid/66.jpg',
    full: '/gallery/full/66.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p67',
    src: '/gallery/grid/67.jpg',
    full: '/gallery/full/67.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p68',
    src: '/gallery/grid/68.jpg',
    full: '/gallery/full/68.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p69',
    src: '/gallery/grid/69.jpg',
    full: '/gallery/full/69.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p70',
    src: '/gallery/grid/70.jpg',
    full: '/gallery/full/70.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p71',
    src: '/gallery/grid/71.jpg',
    full: '/gallery/full/71.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p72',
    src: '/gallery/grid/72.jpg',
    full: '/gallery/full/72.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p73',
    src: '/gallery/grid/73.jpg',
    full: '/gallery/full/73.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p74',
    src: '/gallery/grid/74.jpg',
    full: '/gallery/full/74.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p75',
    src: '/gallery/grid/75.jpg',
    full: '/gallery/full/75.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p76',
    src: '/gallery/grid/76.jpg',
    full: '/gallery/full/76.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p77',
    src: '/gallery/grid/77.jpg',
    full: '/gallery/full/77.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p78',
    src: '/gallery/grid/78.jpg',
    full: '/gallery/full/78.jpg',
    w: 3024,
    h: 4032,
    span: 'tall',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p79',
    src: '/gallery/grid/79.jpg',
    full: '/gallery/full/79.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p80',
    src: '/gallery/grid/80.jpg',
    full: '/gallery/full/80.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p81',
    src: '/gallery/grid/81.jpg',
    full: '/gallery/full/81.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p82',
    src: '/gallery/grid/82.jpg',
    full: '/gallery/full/82.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p83',
    src: '/gallery/grid/83.jpg',
    full: '/gallery/full/83.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p84',
    src: '/gallery/grid/84.jpg',
    full: '/gallery/full/84.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p85',
    src: '/gallery/grid/85.jpg',
    full: '/gallery/full/85.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p86',
    src: '/gallery/grid/86.jpg',
    full: '/gallery/full/86.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p87',
    src: '/gallery/grid/87.jpg',
    full: '/gallery/full/87.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p88',
    src: '/gallery/grid/88.jpg',
    full: '/gallery/full/88.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p89',
    src: '/gallery/grid/89.jpg',
    full: '/gallery/full/89.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p90',
    src: '/gallery/grid/90.jpg',
    full: '/gallery/full/90.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p91',
    src: '/gallery/grid/91.jpg',
    full: '/gallery/full/91.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p92',
    src: '/gallery/grid/92.jpg',
    full: '/gallery/full/92.jpg',
    w: 4016,
    h: 6016,
    span: 'tall',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p93',
    src: '/gallery/grid/93.jpg',
    full: '/gallery/full/93.jpg',
    w: 4016,
    h: 6016,
    span: 'tall',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p94',
    src: '/gallery/grid/94.jpg',
    full: '/gallery/full/94.jpg',
    w: 3840,
    h: 2160,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
  {
    id: 'p95',
    src: '/gallery/grid/95.jpg',
    full: '/gallery/full/95.jpg',
    w: 6016,
    h: 4016,
    span: 'wide',
    alt: 'Photograph by Gaston Genaud',
  },
];
